INSERT INTO institutions (name, ticker, sector, description) VALUES
  ('Industrial and Commercial Bank of China', '1398.HK', 'banking', 'China. Largest bank in the world by total assets, state-owned commercial bank.'),
  ('China Construction Bank', 'CICHY', 'banking', 'China. Second largest bank in China, major state-owned commercial bank.'),
  ('Agricultural Bank of China', 'ACGBY', 'banking', 'China. One of China''s Big Four state-owned banks.'),
  ('Bank of China', 'BACHY', 'banking', 'China. One of China''s Big Four state-owned banks with extensive international operations.'),
  ('HSBC Holdings', 'HSBC', 'banking', 'United Kingdom. Europe''s largest bank by total assets.'),
  ('BNP Paribas', 'BNPQY', 'banking', 'France. Largest bank in the eurozone by total assets.'),
  ('Mitsubishi UFJ Financial Group', 'MUFG', 'banking', 'Japan. Largest financial group in Japan.'),
  ('Credit Agricole Group', 'CRARY', 'banking', 'France. Major French cooperative banking group.'),
  ('Sumitomo Mitsui Financial Group', 'SMFG', 'banking', 'Japan. One of Japan''s three major banking groups.'),
  ('Societe Generale', 'SCGLY', 'banking', 'France. Major French multinational banking and financial services company.'),
  ('Postal Savings Bank of China', '1658.HK', 'banking', 'China. Large state-owned retail bank with the most extensive branch network in China.'),
  ('Bank of Communications', 'BKFCF', 'banking', 'China. Fifth largest commercial bank in China.'),
  ('Mizuho Financial Group', 'MFG', 'banking', 'Japan. One of Japan''s three major banking groups.'),
  ('Groupe BPCE', NULL, 'banking', 'France. Second largest cooperative banking group in France.'),
  ('China Merchants Bank', 'CIHHF', 'banking', 'China. Largest joint-stock commercial bank in China by assets.'),
  ('Royal Bank of Canada', 'RY', 'banking', 'Canada. Largest bank in Canada by market capitalization and assets.'),
  ('Intesa Sanpaolo', 'ISNPY', 'banking', 'Italy. Largest banking group in Italy by total assets.'),
  ('Industrial Bank Co', '601166.SS', 'banking', 'China. Major Chinese joint-stock commercial bank.'),
  ('Shanghai Pudong Development Bank', '600000.SS', 'banking', 'China. Joint-stock commercial bank headquartered in Shanghai.'),
  ('China CITIC Bank', '0998.HK', 'banking', 'China. Major Chinese commercial bank, subsidiary of CITIC Group.'),
  ('China Minsheng Bank', '1988.HK', 'banking', 'China. First privately owned national commercial bank in China.'),
  ('Banco Santander', 'SAN', 'banking', 'Spain. Largest bank in the eurozone by market capitalization.'),
  ('China Everbright Bank', '6818.HK', 'banking', 'China. National joint-stock commercial bank.'),
  ('Ping An Bank', '000001.SZ', 'banking', 'China. Commercial bank subsidiary of Ping An Insurance Group.'),
  ('UniCredit', 'UNCRY', 'banking', 'Italy. Major Italian global banking and financial services company.'),
  ('Rabobank', NULL, 'banking', 'Netherlands. Dutch multinational cooperative banking company.'),
  ('ING Group', 'ING', 'banking', 'Netherlands. Major Dutch multinational banking and financial services corporation.'),
  ('Nordea Bank', 'NRDBY', 'banking', 'Finland. Largest financial services group in the Nordic region.'),
  ('Bank of Montreal', 'BMO', 'banking', 'Canada. Fourth largest bank in Canada, one of the Big Five.'),
  ('Bank of Nova Scotia', 'BNS', 'banking', 'Canada. Third largest bank in Canada by deposits and market capitalization.'),
  ('Canadian Imperial Bank of Commerce', 'CM', 'banking', 'Canada. Fifth largest bank in Canada, one of the Big Five.'),
  ('Commonwealth Bank of Australia', 'CMWAY', 'banking', 'Australia. Largest bank in Australia by market capitalization.'),
  ('Standard Chartered', 'SCBFY', 'banking', 'United Kingdom. Major international bank focused on Asia, Africa, and the Middle East.'),
  ('NatWest Group', 'NWG', 'banking', 'United Kingdom. Major British banking and insurance holding company, formerly RBS.'),
  ('Lloyds Banking Group', 'LYG', 'banking', 'United Kingdom. Largest retail bank in the United Kingdom.'),
  ('DBS Group Holdings', 'DBSDY', 'banking', 'Singapore. Largest bank in Southeast Asia by assets.'),
  ('Westpac Banking Corporation', 'WBK', 'banking', 'Australia. Second oldest and second largest bank in Australia.'),
  ('National Australia Bank', 'NABZY', 'banking', 'Australia. One of Australia''s four largest banks.'),
  ('Oversea-Chinese Banking Corporation', 'OVCHY', 'banking', 'Singapore. Second largest financial services group in Southeast Asia.'),
  ('United Overseas Bank', 'UOVEY', 'banking', 'Singapore. Third largest bank in Southeast Asia by total assets.'),
  ('Commerzbank', 'CRZBY', 'banking', 'Germany. Second largest bank in Germany.'),
  ('BBVA', 'BBVA', 'banking', 'Spain. Second largest bank in Spain by total assets.'),
  ('CaixaBank', 'CAIXY', 'banking', 'Spain. Third largest bank in Spain, largest domestic retail bank.'),
  ('Danske Bank', 'DNKEY', 'banking', 'Denmark. Largest bank in Denmark by total assets.'),
  ('Handelsbanken', 'SVNLY', 'banking', 'Sweden. Major Swedish commercial bank.'),
  ('SEB', 'SKVKY', 'banking', 'Sweden. Major Swedish financial group.'),
  ('Swedbank', 'SWDBY', 'banking', 'Sweden. Major Swedish bank with significant Baltic operations.'),
  ('DNB Bank', 'DNBBY', 'banking', 'Norway. Largest financial services group in Norway.'),
  ('Macquarie Group', 'MQBKY', 'investment_bank', 'Australia. Major global financial services and investment banking firm.'),
  ('Nomura Holdings', 'NMR', 'investment_bank', 'Japan. Largest investment bank in Japan.'),
  ('Daiwa Securities Group', 'DSEEY', 'investment_bank', 'Japan. Second largest securities firm in Japan.'),
  ('Hana Financial Group', 'HNFGF', 'banking', 'South Korea. Major South Korean financial holding company.'),
  ('KB Financial Group', 'KB', 'banking', 'South Korea. Largest financial group in South Korea by assets.'),
  ('Shinhan Financial Group', 'SHG', 'banking', 'South Korea. Major South Korean financial holding company.'),
  ('Woori Financial Group', 'WF', 'banking', 'South Korea. One of South Korea''s largest financial groups.'),
  ('State Bank of India', 'SBIN.NS', 'banking', 'India. Largest bank in India by assets, government-owned.'),
  ('HDFC Bank', 'HDB', 'banking', 'India. Largest private sector bank in India by assets.'),
  ('ICICI Bank', 'IBN', 'banking', 'India. Second largest private sector bank in India.'),
  ('Itau Unibanco', 'ITUB', 'banking', 'Brazil. Largest bank in Latin America by total assets.'),
  ('Banco Bradesco', 'BBD', 'banking', 'Brazil. Second largest private bank in Brazil.'),
  ('Banco do Brasil', 'BDORY', 'banking', 'Brazil. Largest bank in Brazil by assets, state-controlled.'),
  ('Qatar National Bank', 'QNBK.QA', 'banking', 'Qatar. Largest bank in the Middle East and Africa by total assets.'),
  ('First Abu Dhabi Bank', 'FAB.AE', 'banking', 'United Arab Emirates. Largest bank in the UAE.'),
  ('Saudi National Bank', '1180.SR', 'banking', 'Saudi Arabia. Largest bank in Saudi Arabia by total assets.'),
  ('Al Rajhi Bank', 'RJHI.SR', 'banking', 'Saudi Arabia. One of the largest Islamic banks in the world.'),
  ('Resona Holdings', 'RSNHY', 'banking', 'Japan. Major Japanese financial holding company.'),
  ('Raiffeisen Bank International', 'RAIFY', 'banking', 'Austria. Major Austrian banking group with Central and Eastern European operations.'),
  ('Erste Group Bank', 'EBKDY', 'banking', 'Austria. One of the largest financial services providers in Central and Eastern Europe.'),
  ('ABN AMRO Bank', 'AAVMY', 'banking', 'Netherlands. Third largest bank in the Netherlands.'),
  ('Banco Sabadell', 'BNDSF', 'banking', 'Spain. Fifth largest banking group in Spain.'),
  ('KBC Group', 'KBCSY', 'banking', 'Belgium. Major Belgian bank-insurance group.'),
  ('Mediobanca', 'MDIBY', 'investment_bank', 'Italy. Leading Italian investment bank.'),
  ('Hua Xia Bank', '600015.SS', 'banking', 'China. National joint-stock commercial bank.'),
  ('Bank of Beijing', '601169.SS', 'banking', 'China. Largest city commercial bank in China.'),
  ('Bank of Shanghai', '601229.SS', 'banking', 'China. Major Chinese city commercial bank.'),
  ('Bank of Jiangsu', '600919.SS', 'banking', 'China. Major Chinese city commercial bank based in Nanjing.'),
  ('Cathay Financial Holding', 'CATHF', 'banking', 'Taiwan. Largest financial holding company in Taiwan.'),
  ('CTBC Financial Holding', '2891.TW', 'banking', 'Taiwan. Major Taiwanese financial holding company.'),
  ('Malayan Banking Berhad', 'MLYBY', 'banking', 'Malaysia. Largest bank in Malaysia and one of the largest in Southeast Asia.'),
  ('Bangkok Bank', 'BKKLY', 'banking', 'Thailand. Largest commercial bank in Thailand.'),
  ('Kasikornbank', 'KPCPY', 'banking', 'Thailand. One of Thailand''s largest commercial banks.'),
  ('Bank Central Asia', 'BBCAY', 'banking', 'Indonesia. Largest private bank in Indonesia by market capitalization.')
ON CONFLICT DO NOTHING;
